// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZPwjm0WKJTnUX8aS-6QZ2cUdYmBX8kuo',
    appId: '1:474102387652:web:11378fd78307d55e3d0a91',
    messagingSenderId: '474102387652',
    projectId: 'students-2702e',
    authDomain: 'students-2702e.firebaseapp.com',
    storageBucket: 'students-2702e.firebasestorage.app',
    measurementId: 'G-ELKGBVCJ52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxgGfIRRIY8sfhqigDmw4ICv84bFCOXXw',
    appId: '1:474102387652:android:eb27b702cbea17a63d0a91',
    messagingSenderId: '474102387652',
    projectId: 'students-2702e',
    storageBucket: 'students-2702e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaCswh6CMqw5-BX7yqISyboASWkYRGEys',
    appId: '1:474102387652:ios:318c86b7428325f73d0a91',
    messagingSenderId: '474102387652',
    projectId: 'students-2702e',
    storageBucket: 'students-2702e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaCswh6CMqw5-BX7yqISyboASWkYRGEys',
    appId: '1:474102387652:ios:318c86b7428325f73d0a91',
    messagingSenderId: '474102387652',
    projectId: 'students-2702e',
    storageBucket: 'students-2702e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZPwjm0WKJTnUX8aS-6QZ2cUdYmBX8kuo',
    appId: '1:474102387652:web:fd7a75d3266b75083d0a91',
    messagingSenderId: '474102387652',
    projectId: 'students-2702e',
    authDomain: 'students-2702e.firebaseapp.com',
    storageBucket: 'students-2702e.firebasestorage.app',
    measurementId: 'G-H47ESZQ93F',
  );
}
